<?php
/**
 * Created by PhpStorm.
 * User: dempsey
 * Date: 19-3-29
 * Time: 下午5:33
 */

namespace app\widgets;


use app\utils\Debugger;
use yii\helpers\Html;
use yii\widgets\InputWidget;

class SearchInput extends InputWidget
{
    public $template = "{input}{button}";
    public $containerOptions = [];
    public $searchType;
    public $callback;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        Html::addCssClass($this->options, 'form-control');
        Html::addCssClass($this->containerOptions, 'input-group');

    }

    public function run()
    {

        $input = $this->hasModel()
            ? Html::activeTextInput($this->model, $this->attribute, $this->options)
            : Html::textInput($this->name, $this->value, $this->options);

        $pickerAddon = Html::tag('span', '<span  class="glyphicon glyphicon-search" ></span>', ['class' => 'input-group-addon', 'style' => 'cursor:pointer','onclick'=>'onSearch(this)']);
        $input = Html::tag(
            'div',
            strtr($this->template, ['{input}' => $input, '{button}' => $pickerAddon]),
            $this->containerOptions
        );
        echo $input;
        $this->registerAsset();
    }

    public function registerAsset()
    {
        $view = $this->getView();
        $id = $this->options['id'];
        Debugger::debug($id);
        $js = <<< JS
       $('#$id').parent().find('.input-group-addon').click(        function() {
   $('#model_id').text("$id");
   $('#model_type').text("$this->searchType");
   $('#device_name_input').val('');
   $('#device_no_input').val('');
            switch ($this->searchType) {
                case 1:
                    $('#table').bootstrapTable('refreshOptions',{
                      url: '/music-library/query',
                     columns: [{
                    field: 'musicNo',
                title: '音乐编号',
                width: '10%',
            },
                {
                    field: 'musicName',
                    title: '音乐名称',
                }]});
                 
            $('#myModal').modal('show');
            break;
        case 2:
                    $('#table').bootstrapTable('refreshOptions',
                    {
                        url:'/music-arrange/query',
                     columns: [{
                field: 'arrangeNo',
                title: '播期编号',
                width: '10%',
            },
                {
                    field: 'arrangeName',
                    title: '播期名称',
                }]});
                     $('#myModal').modal('show');
                    break;
          }
        });




JS;
        $view->registerJs($js);
    }

   public function render($view, $params = [])
   {
       Debugger::debug('red');
       return parent::render($view, $params); // TODO: Change the autogenerated stub
   }
}
